# Generated by Django 5.2.2 on 2025-06-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestionResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='myapp.faculty'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('course_offering_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=5)),
                ('term_number', models.CharField(max_length=20)),
                ('year_offered', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.instructor')),
            ],
            options={
                'unique_together': {('course', 'section_number', 'term_number', 'year_offered')},
            },
        ),
        migrations.CreateModel(
            name='InstructorRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_description', models.TextField()),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffering')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('post_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobposting'),
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('lab_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=5)),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffering')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffering')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffering')),
                ('lab_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.labsection')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('year_standing', models.IntegerField(blank=True, null=True)),
                ('study_level', models.CharField(max_length=20)),
                ('sin', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('file_link', models.TextField()),
                ('uploaded_at', models.DateField()),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('term_number', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.CreateModel(
            name='TAScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_schedulers', to='myapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_created', to='myapp.tascheduler'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tascheduler'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to='myapp.tascheduler'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='myapp.tascheduler'),
        ),
        migrations.CreateModel(
            name='ApplicationSelectedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.application')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffering')),
            ],
            options={
                'unique_together': {('application', 'course_offering')},
            },
        ),
        migrations.CreateModel(
            name='JobPostingCourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courseoffering')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobposting')),
            ],
            options={
                'unique_together': {('posting', 'course_offering')},
            },
        ),
    ]
