# Generated by Django 5.2.2 on 2025-07-18 01:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'No Longer In Consideration'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positionType', models.CharField(blank=True, max_length=100, null=True)),
                ('workload', models.CharField(blank=True, max_length=20, null=True)),
                ('disciplineRankings', models.JSONField()),
                ('citizenshipStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('residingInKelowna', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('fullTimeEnrollment', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('hasOtherPositions', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('otherPositionHours', models.PositiveIntegerField(blank=True, help_text='Hours per week for other positions', null=True)),
            ],
            options={
                'db_table': 'myapp_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'myapp_applicationshortlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('course_offering_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'myapp_course_offerings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'myapp_jobposting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SharedSession',
            fields=[
                ('shared_session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'myapp_sharedsessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('study_level', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'myapp_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'myapp_tascheduler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'myapp_term',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_hours', models.CharField(choices=[('6', '6 hours'), ('12', '12 hours')], default='6', max_length=2)),
                ('role', models.CharField(choices=[('ta', 'Teaching Assistant')], default='ta', max_length=3)),
                ('offer_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_deadline', models.DateTimeField(help_text='Deadline for student to respond')),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('student_response', models.TextField(blank=True, help_text="Student's response message", null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('course_offering', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.courseoffering')),
                ('created_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='offers_created', to='api.tascheduler')),
                ('shared_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sharedsession')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'myapp_offer',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_hours', models.CharField(choices=[('6', '6 hours'), ('12', '12 hours')], default='6', max_length=2)),
                ('role', models.CharField(choices=[('ta', 'Teaching Assistant')], default='ta', max_length=3)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to='api.tascheduler')),
                ('course_offering', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.courseoffering')),
                ('shared_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sharedsession')),
                ('student', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.offer')),
            ],
            options={
                'db_table': 'myapp_assignment',
                'ordering': ['-assigned_date'],
                'managed': True,
            },
        ),
    ]
