# Generated by Django 5.2.2 on 2025-07-10 19:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'myapp_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateField(help_text='Term start date')),
                ('end', models.DateField(help_text='Term end date')),
                ('startCalendarYear', models.IntegerField()),
                ('endCalendarYear', models.IntegerField()),
                ('academicYear', models.CharField(help_text="e.g., '2025/26'", max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('term_type', models.CharField(blank=True, choices=[('winter', 'Winter'), ('summer', 'Summer'), ('full_year', 'Full Year')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'myapp_term',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=9, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True, max_length=500, null=True)),
                ('course_level', models.CharField(blank=True, max_length=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api.department')),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('course_offering_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_number', models.CharField(help_text="Section number (e.g., '001', 'L01')", max_length=3)),
                ('academic_term', models.ForeignKey(help_text='Academic term when this course is offered', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='course_api.term')),
                ('course', models.ForeignKey(help_text='The course this offering is for', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='course_api.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor teaching this course offering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='course_api.instructor')),
            ],
            options={
                'db_table': 'course_offerings',
                'ordering': ['-academic_term__startCalendarYear', 'course__course_number', 'section_number'],
                'managed': True,
                'unique_together': {('course', 'section_number', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='InstructorRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('request_description', models.TextField()),
                ('course_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_api.courseoffering')),
                ('instructor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_api.instructor')),
            ],
            options={
                'db_table': 'instructor_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week for this time slot', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['day', 'start_time'],
                'managed': True,
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='SharedSession',
            fields=[
                ('shared_session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_type', models.CharField(max_length=10)),
                ('section_number', models.CharField(help_text="Lab section number (e.g., 'L01', 'T01')", max_length=3)),
                ('academic_term', models.ForeignKey(help_text='Academic term when this lab section is offered', on_delete=django.db.models.deletion.CASCADE, related_name='lab_sections', to='course_api.term')),
                ('course', models.ForeignKey(help_text='The course this lab section is for', on_delete=django.db.models.deletion.CASCADE, related_name='lab_sections', to='course_api.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor or TA teaching this lab section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_sections', to='course_api.instructor')),
                ('time_slots', models.ManyToManyField(blank=True, help_text='Time slots when this lab section meets', related_name='lab_sections', to='course_api.timeslot')),
            ],
            options={
                'db_table': 'lab_sections',
                'ordering': ['-academic_term__startCalendarYear', 'course__course_number', 'section_number'],
                'managed': True,
                'unique_together': {('course', 'section_number', 'academic_term')},
            },
        ),
    ]
