# Generated by Django 5.2.2 on 2025-07-04 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'myapp_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('term_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('year', models.CharField(help_text='Academic year (e.g., 2024)', max_length=4)),
                ('term_number', models.CharField(choices=[('1', 'Term 1'), ('2', 'Term 2')], help_text='Term number within the academic year', max_length=1)),
                ('term', models.CharField(choices=[('winter', 'Winter'), ('summer', 'Summer')], help_text='Term season', max_length=7)),
                ('start_date', models.DateField(help_text='Term start date')),
                ('end_date', models.DateField(help_text='Term end date')),
            ],
            options={
                'db_table': 'academic_terms',
                'ordering': ['-year', 'term_number'],
                'managed': True,
                'unique_together': {('year', 'term_number', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=9, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True, max_length=500, null=True)),
                ('course_level', models.CharField(blank=True, max_length=4)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_api.department')),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week for this time slot', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['day', 'start_time'],
                'managed': True,
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('lab_section_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_number', models.CharField(help_text="Lab section number (e.g., 'L01', 'T01')", max_length=3)),
                ('academic_term', models.ForeignKey(help_text='Academic term when this lab section is offered', on_delete=django.db.models.deletion.CASCADE, related_name='lab_sections', to='course_api.academicterm')),
                ('course', models.ForeignKey(help_text='The course this lab section is for', on_delete=django.db.models.deletion.CASCADE, related_name='lab_sections', to='course_api.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor or TA teaching this lab section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_sections', to='course_api.instructor')),
                ('time_slots', models.ManyToManyField(blank=True, help_text='Time slots when this lab section meets', related_name='lab_sections', to='course_api.timeslot')),
            ],
            options={
                'db_table': 'lab_sections',
                'ordering': ['-academic_term__year', 'course__course_number', 'section_number'],
                'managed': True,
                'unique_together': {('course', 'section_number', 'academic_term')},
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('course_offering_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('section_number', models.CharField(help_text="Section number (e.g., '001', 'L01')", max_length=3)),
                ('academic_term', models.ForeignKey(help_text='Academic term when this course is offered', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='course_api.academicterm')),
                ('course', models.ForeignKey(help_text='The course this offering is for', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='course_api.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor teaching this course offering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings', to='course_api.instructor')),
                ('time_slots', models.ManyToManyField(blank=True, help_text='Time slots when this course meets', related_name='course_offerings', to='course_api.timeslot')),
            ],
            options={
                'db_table': 'course_offerings',
                'ordering': ['-academic_term__year', 'course__course_number', 'section_number'],
                'managed': True,
                'unique_together': {('course', 'section_number', 'academic_term')},
            },
        ),
    ]
