# Generated by Django 5.2.2 on 2025-07-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='myapp_courses',
        ),
        migrations.AlterModelTable(
            name='courseoffering',
            table='myapp_course_offerings',
        ),
        migrations.AlterModelTable(
            name='instructorrequest',
            table='myapp_instructor_requests',
        ),
        migrations.AlterModelTable(
            name='term',
            table='myapp_academic_terms',
        ),
    ]
