# Generated by Django 5.2.2 on 2025-07-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_alter_course_table_alter_courseoffering_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharedsession',
            table='myapp_sharedsessions',
        ),
    ]
