# Generated by Django 5.2.2 on 2025-07-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0003_alter_sharedsession_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='term',
            table='myapp_term',
        ),
    ]
