# Generated by Django 5.2.2 on 2025-07-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expected_graduation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
