events {}

http {
    # define backend server
    upstream backend {
        server backend:8000;
    }

    # define frontend server
    upstream frontend {
        server frontend:5173;
    }

    server {
        # listen at port 80 for both IPv4 and IPv6
        listen 80;
        listen [::]:80;

        # process route for root (/)
        location / {
            proxy_pass http://frontend;
        }

        # process route for the api calls
        location /api/ {
            proxy_pass http://backend;
        }
    }
}