# Generated by Django 5.2.2 on 2025-06-26 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'myapp_faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'myapp_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('year_standing', models.IntegerField(blank=True, null=True)),
                ('study_level', models.CharField(max_length=20)),
                ('sin', models.CharField(blank=True, max_length=11, null=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'myapp_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'myapp_tascheduler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positionType', models.CharField(blank=True, choices=[('UTA', 'Undergraduate Teaching Assistant'), ('GTA2', "Graduate Teaching Assistant 2 (Master's Student)"), ('GTA1', 'Graduate Teaching Assistant 1 (Ph.D student)')], max_length=100, null=True)),
                ('workload', models.CharField(blank=True, choices=[('6', '6 hours'), ('12', '12 hours')], max_length=20, null=True)),
                ('disciplineRankings', models.JSONField()),
                ('citizenshipStatus', models.CharField(blank=True, choices=[('citizen', 'Canadian Citizen'), ('pr', 'Permanent Resident'), ('international', 'International Student')], max_length=50, null=True)),
                ('residingInKelowna', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('fullTimeEnrollment', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('hasOtherPositions', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('otherPositionHours', models.PositiveIntegerField(blank=True, help_text='Hours per week for other positions', null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.student')),
            ],
            options={
                'db_table': 'myapp_application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('file_link', models.TextField()),
                ('uploaded_at', models.DateField()),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.application')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.student')),
            ],
            options={
                'db_table': 'myapp_document',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('post_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('closed', 'Closed'), ('open', 'Open')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.tascheduler')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.faculty')),
            ],
            options={
                'db_table': 'myapp_jobposting',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.jobposting'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateField(help_text='Term start date')),
                ('end', models.DateField(help_text='Term end date')),
                ('startCalendarYear', models.IntegerField()),
                ('endCalendarYear', models.IntegerField()),
                ('academicYear', models.CharField(help_text="e.g., '2025/26'", max_length=10)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('term_type', models.CharField(blank=True, choices=[('winter', 'Winter'), ('summer', 'Summer'), ('full_year', 'Full Year')], max_length=20, null=True)),
                ('subsetOf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subterms', to='ajp.term')),
            ],
            options={
                'db_table': 'myapp_term',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='termSelection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ajp.term'),
        ),
        migrations.CreateModel(
            name='JobPostingQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_questions', to='ajp.jobposting')),
            ],
            options={
                'db_table': 'myapp_jobpostingquestion',
                'managed': True,
                'unique_together': {('posting', 'question_text')},
            },
        ),
    ]
